drop table parameter if exists;

create table parameter (    id varchar(255) generated by default as identity,    type varchar(255) not null,    code varchar(255),    name varchar(255),    primary key (id));